def get_feature_columns():
    # 确定特征、类别特征、数值特征
    feature_columns = [
        'hour',
        'day_of_week',
        'is_weekend',
        'half',
        'wtNm',
        'wtTemp',
        'wtHumi',
        'wtWinp',
        'wtRainfall',
        '交通设施服务_count',
        '住宿服务_count',
        '体育休闲服务_count',
        '公共设施_count',
        '公司企业_count',
        '医疗保健服务_count',
        '商务住宅_count',
        '地名地址信息_count',
        '室内设施_count',
        '摩托车服务_count',
        '政府机构及社会团体_count',
        '汽车服务_count',
        '汽车维修_count',
        '汽车销售_count',
        '生活服务_count',
        '科教文化服务_count',
        '虚拟数据_count',
        '购物服务_count',
        '道路附属设施_count',
        '金融保险服务_count',
        '风景名胜_count',
        '餐饮服务_count',
        # '住宅_count',
        # '物流速递_count',
    ]
    categorical_columns = [
        'wtNm',
        'wtWinp',
        'is_weekend',
        'half',
        'hour',
        'day_of_week',
    ]
    numeric_columns = [
        'wtTemp',
        'wtHumi',
        'wtRainfall',
        '交通设施服务_count',
        '住宿服务_count',
        '体育休闲服务_count',
        '公共设施_count',
        '公司企业_count',
        '医疗保健服务_count',
        '商务住宅_count',
        '地名地址信息_count',
        '室内设施_count',
        '摩托车服务_count',
        '政府机构及社会团体_count',
        '汽车服务_count',
        '汽车维修_count',
        '汽车销售_count',
        '生活服务_count',
        '科教文化服务_count',
        '虚拟数据_count',
        '购物服务_count',
        '道路附属设施_count',
        '金融保险服务_count',
        '风景名胜_count',
        '餐饮服务_count',
        # '住宅_count',
        # '物流速递_count',
    ]
    weather_columns = [
        'wtNm',
        'wtTemp',
        'wtHumi',
        'wtWinp',
        'wtRainfall'
    ]

    return feature_columns, categorical_columns, numeric_columns, weather_columns
